# Generated by Django 4.2.5 on 2023-10-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_comment_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='comment_created_at'),
        ),
    ]
