# Generated by Django 4.2.5 on 2023-10-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_othello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='comment_name')),
                ('record', models.CharField(max_length=200, verbose_name='record')),
                ('size', models.SmallIntegerField(verbose_name='size')),
                ('recorded_time', models.DateTimeField(auto_now=True, verbose_name='recorded_at')),
            ],
        ),
    ]
