# Generated by Django 4.2.5 on 2023-10-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_record_othello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_othello',
            name='name',
            field=models.CharField(max_length=100, verbose_name='player_name'),
        ),
    ]
