# Generated by Django 4.2.5 on 2023-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_record_othello_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='player_name')),
                ('score', models.CharField(max_length=200, verbose_name='score')),
                ('recorded_time', models.DateField(auto_now=True, verbose_name='recorded_at')),
            ],
        ),
    ]
